import globals from 'globals'
import base from '@jakobmelchard/config/eslint'

const dsl = ['grammar', 'seq', 'choice', 'repeat', 'repeat1', 'optional', 'field', 'alias', 'token']

// lib/ runs in Node, browsers and Workers; scripts/ and test/ on Node.
export default [
  ...base,
  { languageOptions: { globals: { ...globals.node, ...globals.browser } } },
  // tree-sitter injects its DSL as globals when it loads the grammar.
  { files: ['grammar.js'], languageOptions: { globals: Object.fromEntries(dsl.map(k => [k, 'readonly'])) } },
  // src/ is generated by tree-sitter.
  { ignores: ['src/**', 'build/**', '.build/**'] },
]
