// Code generated by scripts/parser-sum.js; DO NOT EDIT.

package tree_sitter_workline

// parserSum is the SHA-256 of src/parser.c, so Go rebuilds the cgo parser
// whenever the grammar changes.
const parserSum = "7f336614c2dc43ed91ae6e1552514f05f08c7b84620e14cceb0d1bfb968c5100"
