// Writes bindings/go/parser_sum.go with the SHA-256 of src/parser.c.
// cgo does not track src/parser.c (binding.go #includes it from outside the
// package), so Go's build cache, locally or restored in CI, can keep testing
// a stale parser. A Go file that changes with the parser makes it rebuild.
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'

const root = new URL('..', import.meta.url)
const sum = createHash('sha256').update(readFileSync(new URL('src/parser.c', root))).digest('hex')
writeFileSync(new URL('bindings/go/parser_sum.go', root), `// Code generated by scripts/parser-sum.js; DO NOT EDIT.

package tree_sitter_workline

// parserSum is the SHA-256 of src/parser.c, so Go rebuilds the cgo parser
// whenever the grammar changes.
const parserSum = "${sum}"
`)
