/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 68
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 25
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_SLASH = 2,
  anon_sym_COMMA = 3,
  sym_name = 4,
  sym_times = 5,
  anon_sym_DASH = 6,
  aux_sym_target_token1 = 7,
  anon_sym_PLUS = 8,
  anon_sym_QMARK_PLUS = 9,
  aux_sym_weight_token1 = 10,
  anon_sym_AT = 11,
  sym_ask_weight = 12,
  anon_sym_PERCENT = 13,
  aux_sym_rest_token1 = 14,
  aux_sym__gap_num_token1 = 15,
  aux_sym__num_imm_token1 = 16,
  sym_number = 17,
  sym_document = 18,
  sym_line = 19,
  sym_group = 20,
  sym_target = 21,
  sym_mods = 22,
  sym_defaults = 23,
  sym__mod = 24,
  sym_weight = 25,
  sym__weight_first = 26,
  sym__legacy_weight = 27,
  sym_percent = 28,
  sym__percent_first = 29,
  sym_rest = 30,
  sym__rest_first = 31,
  sym_rpe = 32,
  sym__gap_num = 33,
  sym__ask = 34,
  sym__num_imm = 35,
  aux_sym_document_repeat1 = 36,
  aux_sym_line_repeat1 = 37,
  aux_sym_mods_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_SLASH] = "/",
  [anon_sym_COMMA] = ",",
  [sym_name] = "name",
  [sym_times] = "times",
  [anon_sym_DASH] = "-",
  [aux_sym_target_token1] = "unit",
  [anon_sym_PLUS] = "ask",
  [anon_sym_QMARK_PLUS] = "ask_weight",
  [aux_sym_weight_token1] = "unit",
  [anon_sym_AT] = "@",
  [sym_ask_weight] = "ask_weight",
  [anon_sym_PERCENT] = "%",
  [aux_sym_rest_token1] = "unit",
  [aux_sym__gap_num_token1] = "number",
  [aux_sym__num_imm_token1] = "number",
  [sym_number] = "number",
  [sym_document] = "document",
  [sym_line] = "line",
  [sym_group] = "group",
  [sym_target] = "target",
  [sym_mods] = "mods",
  [sym_defaults] = "defaults",
  [sym__mod] = "_mod",
  [sym_weight] = "weight",
  [sym__weight_first] = "weight",
  [sym__legacy_weight] = "weight",
  [sym_percent] = "percent",
  [sym__percent_first] = "percent",
  [sym_rest] = "rest",
  [sym__rest_first] = "rest",
  [sym_rpe] = "rpe",
  [sym__gap_num] = "_gap_num",
  [sym__ask] = "_ask",
  [sym__num_imm] = "_num_imm",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_line_repeat1] = "line_repeat1",
  [aux_sym_mods_repeat1] = "mods_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_name] = sym_name,
  [sym_times] = sym_times,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_target_token1] = aux_sym_target_token1,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_QMARK_PLUS] = sym_ask_weight,
  [aux_sym_weight_token1] = aux_sym_target_token1,
  [anon_sym_AT] = anon_sym_AT,
  [sym_ask_weight] = sym_ask_weight,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_rest_token1] = aux_sym_target_token1,
  [aux_sym__gap_num_token1] = sym_number,
  [aux_sym__num_imm_token1] = sym_number,
  [sym_number] = sym_number,
  [sym_document] = sym_document,
  [sym_line] = sym_line,
  [sym_group] = sym_group,
  [sym_target] = sym_target,
  [sym_mods] = sym_mods,
  [sym_defaults] = sym_defaults,
  [sym__mod] = sym__mod,
  [sym_weight] = sym_weight,
  [sym__weight_first] = sym_weight,
  [sym__legacy_weight] = sym_weight,
  [sym_percent] = sym_percent,
  [sym__percent_first] = sym_percent,
  [sym_rest] = sym_rest,
  [sym__rest_first] = sym_rest,
  [sym_rpe] = sym_rpe,
  [sym__gap_num] = sym__gap_num,
  [sym__ask] = sym__ask,
  [sym__num_imm] = sym__num_imm,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_line_repeat1] = aux_sym_line_repeat1,
  [aux_sym_mods_repeat1] = aux_sym_mods_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_times] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_target_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_QMARK_PLUS] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_weight_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_ask_weight] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_rest_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__gap_num_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__num_imm_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_target] = {
    .visible = true,
    .named = true,
  },
  [sym_mods] = {
    .visible = true,
    .named = true,
  },
  [sym_defaults] = {
    .visible = true,
    .named = true,
  },
  [sym__mod] = {
    .visible = false,
    .named = true,
  },
  [sym_weight] = {
    .visible = true,
    .named = true,
  },
  [sym__weight_first] = {
    .visible = true,
    .named = true,
  },
  [sym__legacy_weight] = {
    .visible = true,
    .named = true,
  },
  [sym_percent] = {
    .visible = true,
    .named = true,
  },
  [sym__percent_first] = {
    .visible = true,
    .named = true,
  },
  [sym_rest] = {
    .visible = true,
    .named = true,
  },
  [sym__rest_first] = {
    .visible = true,
    .named = true,
  },
  [sym_rpe] = {
    .visible = true,
    .named = true,
  },
  [sym__gap_num] = {
    .visible = false,
    .named = true,
  },
  [sym__ask] = {
    .visible = false,
    .named = true,
  },
  [sym__num_imm] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mods_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_ask = 1,
  field_defaults = 2,
  field_max = 3,
  field_min = 4,
  field_name = 5,
  field_sets = 6,
  field_target = 7,
  field_unit = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_ask] = "ask",
  [field_defaults] = "defaults",
  [field_max] = "max",
  [field_min] = "min",
  [field_name] = "name",
  [field_sets] = "sets",
  [field_target] = "target",
  [field_unit] = "unit",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 3},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 2},
  [9] = {.index = 14, .length = 2},
  [10] = {.index = 16, .length = 1},
  [11] = {.index = 17, .length = 2},
  [12] = {.index = 19, .length = 1},
  [13] = {.index = 20, .length = 1},
  [14] = {.index = 21, .length = 2},
  [15] = {.index = 23, .length = 2},
  [16] = {.index = 25, .length = 3},
  [17] = {.index = 28, .length = 2},
  [18] = {.index = 30, .length = 2},
  [19] = {.index = 32, .length = 3},
  [20] = {.index = 35, .length = 2},
  [21] = {.index = 37, .length = 2},
  [22] = {.index = 39, .length = 3},
  [23] = {.index = 42, .length = 3},
  [24] = {.index = 45, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_min, 0},
  [2] =
    {field_sets, 0},
    {field_target, 2},
  [4] =
    {field_defaults, 2},
  [5] =
    {field_ask, 0, .inherited = true},
    {field_unit, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [8] =
    {field_unit, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [10] =
    {field_ask, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [12] =
    {field_min, 0},
    {field_unit, 1},
  [14] =
    {field_ask, 1},
    {field_min, 0},
  [16] =
    {field_value, 1},
  [17] =
    {field_unit, 1},
    {field_value, 0},
  [19] =
    {field_value, 0},
  [20] =
    {field_defaults, 3},
  [21] =
    {field_defaults, 4},
    {field_name, 0},
  [23] =
    {field_max, 2},
    {field_min, 0},
  [25] =
    {field_ask, 2},
    {field_min, 0},
    {field_unit, 1},
  [28] =
    {field_unit, 2},
    {field_value, 1},
  [30] =
    {field_ask, 2},
    {field_value, 1},
  [32] =
    {field_ask, 2},
    {field_unit, 1},
    {field_value, 0},
  [35] =
    {field_ask, 2},
    {field_value, 0},
  [37] =
    {field_defaults, 5},
    {field_name, 0},
  [39] =
    {field_max, 2},
    {field_min, 0},
    {field_unit, 3},
  [42] =
    {field_ask, 3},
    {field_max, 2},
    {field_min, 0},
  [45] =
    {field_ask, 4},
    {field_max, 2},
    {field_min, 0},
    {field_unit, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(17);
      if (lookahead == '%') ADVANCE(35);
      if (lookahead == '+') ADVANCE(30);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '?') ADVANCE(6);
      if (lookahead == '@') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead == 'K' ||
          lookahead == 'k') ADVANCE(11);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(9);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(29);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(28);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(28);
      if (lookahead == 'X' ||
          lookahead == 'x' ||
          lookahead == 0xd7) ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(2);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead == '@') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(2);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '@') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(3);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '?') ADVANCE(6);
      if (lookahead == '@') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead == 'X' ||
          lookahead == 'x' ||
          lookahead == 0xd7) ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(3);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '?') ADVANCE(6);
      if (lookahead == '@') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead == 'X' ||
          lookahead == 'x' ||
          lookahead == 0xd7) ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '%', 35,
        '?', 6,
        '@', 33,
        'K', 10,
        'k', 10,
        'L', 9,
        'l', 9,
        'M', 37,
        'm', 37,
        'S', 36,
        's', 36,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 6:
      if (lookahead == '+') ADVANCE(31);
      END_STATE();
    case 7:
      if (lookahead == '+') ADVANCE(34);
      END_STATE();
    case 8:
      if (lookahead == '?') ADVANCE(6);
      if (lookahead == '@') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 9:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(32);
      END_STATE();
    case 11:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(32);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 17:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(17);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '?') ADVANCE(6);
      if (lookahead == '@') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead == 'X' ||
          lookahead == 'x' ||
          lookahead == 0xd7) ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 18:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(19);
      if (lookahead == '+') ADVANCE(30);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '@') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead == 'K' ||
          lookahead == 'k') ADVANCE(11);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(9);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(29);
      if (lookahead == 'R' ||
          lookahead == 'S' ||
          lookahead == 'r' ||
          lookahead == 's') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 19:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(19);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '@') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < '/' || '9' < lookahead)) ADVANCE(25);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_times);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_target_token1);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_target_token1);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_QMARK_PLUS);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_weight_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_ask_weight);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_rest_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_rest_token1);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__gap_num_token1);
      if (lookahead == '.') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__gap_num_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym__num_imm_token1);
      if (lookahead == '.') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym__num_imm_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 18},
  [5] = {.lex_state = 18},
  [6] = {.lex_state = 18},
  [7] = {.lex_state = 18},
  [8] = {.lex_state = 18},
  [9] = {.lex_state = 18},
  [10] = {.lex_state = 18},
  [11] = {.lex_state = 18},
  [12] = {.lex_state = 18},
  [13] = {.lex_state = 18},
  [14] = {.lex_state = 18},
  [15] = {.lex_state = 18},
  [16] = {.lex_state = 18},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 18},
  [22] = {.lex_state = 18},
  [23] = {.lex_state = 18},
  [24] = {.lex_state = 18},
  [25] = {.lex_state = 18},
  [26] = {.lex_state = 20},
  [27] = {.lex_state = 18},
  [28] = {.lex_state = 18},
  [29] = {.lex_state = 18},
  [30] = {.lex_state = 20},
  [31] = {.lex_state = 18},
  [32] = {.lex_state = 18},
  [33] = {.lex_state = 18},
  [34] = {.lex_state = 18},
  [35] = {.lex_state = 18},
  [36] = {.lex_state = 18},
  [37] = {.lex_state = 18},
  [38] = {.lex_state = 18},
  [39] = {.lex_state = 18},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 18},
  [46] = {.lex_state = 18},
  [47] = {.lex_state = 18},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 20},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 5},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 20},
  [56] = {.lex_state = 20},
  [57] = {.lex_state = 20},
  [58] = {.lex_state = 18},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 20},
  [67] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_times] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [aux_sym_target_token1] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_QMARK_PLUS] = ACTIONS(1),
    [aux_sym_weight_token1] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_ask_weight] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [aux_sym_rest_token1] = ACTIONS(1),
    [aux_sym__gap_num_token1] = ACTIONS(1),
    [aux_sym__num_imm_token1] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(67),
    [sym_line] = STATE(61),
    [sym_group] = STATE(44),
    [aux_sym_document_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_name] = ACTIONS(7),
    [sym_number] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_ask_weight,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    STATE(29), 1,
      sym__legacy_weight,
    STATE(49), 1,
      sym_mods,
    STATE(52), 1,
      sym__gap_num,
    ACTIONS(11), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
    STATE(3), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [33] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(21), 1,
      sym_ask_weight,
    STATE(29), 1,
      sym__legacy_weight,
    STATE(52), 1,
      sym__gap_num,
    ACTIONS(19), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
    STATE(4), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [63] = 7,
    ACTIONS(25), 1,
      anon_sym_AT,
    ACTIONS(28), 1,
      sym_ask_weight,
    ACTIONS(31), 1,
      aux_sym__gap_num_token1,
    STATE(29), 1,
      sym__legacy_weight,
    STATE(52), 1,
      sym__gap_num,
    ACTIONS(23), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
    STATE(4), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [93] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(36), 1,
      sym_ask_weight,
    STATE(29), 1,
      sym__legacy_weight,
    STATE(52), 1,
      sym__gap_num,
    ACTIONS(34), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(12), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [121] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(38), 1,
      sym_ask_weight,
    STATE(29), 1,
      sym__legacy_weight,
    STATE(52), 1,
      sym__gap_num,
    ACTIONS(34), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(11), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [149] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(42), 1,
      sym_ask_weight,
    STATE(29), 1,
      sym__legacy_weight,
    STATE(52), 1,
      sym__gap_num,
    ACTIONS(40), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(10), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [177] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(46), 1,
      sym_ask_weight,
    STATE(29), 1,
      sym__legacy_weight,
    STATE(52), 1,
      sym__gap_num,
    ACTIONS(44), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(13), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [205] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(50), 1,
      sym_ask_weight,
    STATE(29), 1,
      sym__legacy_weight,
    STATE(52), 1,
      sym__gap_num,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(14), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [233] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(21), 1,
      sym_ask_weight,
    STATE(29), 1,
      sym__legacy_weight,
    STATE(52), 1,
      sym__gap_num,
    ACTIONS(52), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(4), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [261] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(21), 1,
      sym_ask_weight,
    STATE(29), 1,
      sym__legacy_weight,
    STATE(52), 1,
      sym__gap_num,
    ACTIONS(54), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(4), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [289] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(21), 1,
      sym_ask_weight,
    STATE(29), 1,
      sym__legacy_weight,
    STATE(52), 1,
      sym__gap_num,
    ACTIONS(54), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(4), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [317] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(21), 1,
      sym_ask_weight,
    STATE(29), 1,
      sym__legacy_weight,
    STATE(52), 1,
      sym__gap_num,
    ACTIONS(56), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(4), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [345] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(21), 1,
      sym_ask_weight,
    STATE(29), 1,
      sym__legacy_weight,
    STATE(52), 1,
      sym__gap_num,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(4), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [373] = 4,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      aux_sym_target_token1,
    ACTIONS(66), 1,
      anon_sym_PLUS,
    ACTIONS(60), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [392] = 4,
    ACTIONS(70), 1,
      anon_sym_PLUS,
    ACTIONS(72), 1,
      aux_sym_weight_token1,
    STATE(36), 1,
      sym__ask,
    ACTIONS(68), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [411] = 9,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(74), 1,
      anon_sym_QMARK_PLUS,
    ACTIONS(76), 1,
      sym_number,
    STATE(5), 1,
      sym__legacy_weight,
    STATE(6), 1,
      sym__rest_first,
    STATE(7), 1,
      sym_rpe,
    STATE(8), 1,
      sym__weight_first,
    STATE(9), 1,
      sym__percent_first,
    STATE(54), 1,
      sym_defaults,
  [439] = 9,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(74), 1,
      anon_sym_QMARK_PLUS,
    ACTIONS(76), 1,
      sym_number,
    STATE(5), 1,
      sym__legacy_weight,
    STATE(6), 1,
      sym__rest_first,
    STATE(7), 1,
      sym_rpe,
    STATE(8), 1,
      sym__weight_first,
    STATE(9), 1,
      sym__percent_first,
    STATE(62), 1,
      sym_defaults,
  [467] = 9,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(74), 1,
      anon_sym_QMARK_PLUS,
    ACTIONS(76), 1,
      sym_number,
    STATE(5), 1,
      sym__legacy_weight,
    STATE(6), 1,
      sym__rest_first,
    STATE(7), 1,
      sym_rpe,
    STATE(8), 1,
      sym__weight_first,
    STATE(9), 1,
      sym__percent_first,
    STATE(53), 1,
      sym_defaults,
  [495] = 9,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(74), 1,
      anon_sym_QMARK_PLUS,
    ACTIONS(76), 1,
      sym_number,
    STATE(5), 1,
      sym__legacy_weight,
    STATE(6), 1,
      sym__rest_first,
    STATE(7), 1,
      sym_rpe,
    STATE(8), 1,
      sym__weight_first,
    STATE(9), 1,
      sym__percent_first,
    STATE(60), 1,
      sym_defaults,
  [523] = 3,
    ACTIONS(80), 1,
      anon_sym_PLUS,
    STATE(38), 1,
      sym__ask,
    ACTIONS(78), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [539] = 3,
    ACTIONS(84), 1,
      anon_sym_PLUS,
    STATE(39), 1,
      sym__ask,
    ACTIONS(82), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [555] = 3,
    ACTIONS(88), 1,
      aux_sym_target_token1,
    ACTIONS(90), 1,
      anon_sym_PLUS,
    ACTIONS(86), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [571] = 2,
    ACTIONS(94), 1,
      anon_sym_PLUS,
    ACTIONS(92), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [584] = 2,
    ACTIONS(98), 1,
      anon_sym_PLUS,
    ACTIONS(96), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [597] = 7,
    ACTIONS(7), 1,
      sym_name,
    ACTIONS(9), 1,
      sym_number,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
    ACTIONS(102), 1,
      anon_sym_LF,
    STATE(30), 1,
      aux_sym_document_repeat1,
    STATE(44), 1,
      sym_group,
    STATE(59), 1,
      sym_line,
  [619] = 1,
    ACTIONS(104), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [629] = 3,
    ACTIONS(108), 1,
      anon_sym_PLUS,
    STATE(45), 1,
      sym__ask,
    ACTIONS(106), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [643] = 1,
    ACTIONS(110), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [653] = 7,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      anon_sym_LF,
    ACTIONS(117), 1,
      sym_name,
    ACTIONS(120), 1,
      sym_number,
    STATE(30), 1,
      aux_sym_document_repeat1,
    STATE(44), 1,
      sym_group,
    STATE(64), 1,
      sym_line,
  [675] = 1,
    ACTIONS(123), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [685] = 3,
    ACTIONS(127), 1,
      anon_sym_PLUS,
    STATE(46), 1,
      sym__ask,
    ACTIONS(125), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [699] = 1,
    ACTIONS(129), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [709] = 1,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [719] = 1,
    ACTIONS(133), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [729] = 1,
    ACTIONS(135), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [739] = 1,
    ACTIONS(137), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [749] = 1,
    ACTIONS(139), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [759] = 1,
    ACTIONS(141), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [769] = 3,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      aux_sym_line_repeat1,
    ACTIONS(143), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
  [781] = 4,
    ACTIONS(150), 1,
      anon_sym_SLASH,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      aux_sym_line_repeat1,
    ACTIONS(148), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [795] = 4,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    ACTIONS(156), 1,
      anon_sym_SLASH,
    STATE(41), 1,
      aux_sym_line_repeat1,
    ACTIONS(154), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [809] = 4,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    ACTIONS(160), 1,
      anon_sym_SLASH,
    STATE(40), 1,
      aux_sym_line_repeat1,
    ACTIONS(158), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [823] = 4,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    ACTIONS(164), 1,
      anon_sym_SLASH,
    STATE(43), 1,
      aux_sym_line_repeat1,
    ACTIONS(162), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [837] = 1,
    ACTIONS(166), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [845] = 1,
    ACTIONS(168), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [853] = 1,
    ACTIONS(170), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [861] = 1,
    ACTIONS(143), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
  [868] = 1,
    ACTIONS(172), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
  [875] = 1,
    ACTIONS(112), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_name,
      sym_number,
  [882] = 3,
    ACTIONS(174), 1,
      aux_sym_weight_token1,
    ACTIONS(176), 1,
      anon_sym_PERCENT,
    ACTIONS(178), 1,
      aux_sym_rest_token1,
  [892] = 3,
    ACTIONS(180), 1,
      aux_sym_weight_token1,
    ACTIONS(182), 1,
      anon_sym_PERCENT,
    ACTIONS(184), 1,
      aux_sym_rest_token1,
  [902] = 1,
    ACTIONS(186), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [907] = 1,
    ACTIONS(188), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [912] = 2,
    ACTIONS(190), 1,
      sym_number,
    STATE(2), 1,
      sym_target,
  [919] = 2,
    ACTIONS(9), 1,
      sym_number,
    STATE(48), 1,
      sym_group,
  [926] = 2,
    ACTIONS(9), 1,
      sym_number,
    STATE(42), 1,
      sym_group,
  [933] = 2,
    ACTIONS(192), 1,
      aux_sym__num_imm_token1,
    STATE(16), 1,
      sym__num_imm,
  [940] = 2,
    ACTIONS(194), 1,
      ts_builtin_sym_end,
    ACTIONS(196), 1,
      anon_sym_LF,
  [947] = 1,
    ACTIONS(198), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [952] = 2,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
    ACTIONS(196), 1,
      anon_sym_LF,
  [959] = 1,
    ACTIONS(200), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [964] = 1,
    ACTIONS(202), 1,
      anon_sym_SLASH,
  [968] = 1,
    ACTIONS(196), 1,
      anon_sym_LF,
  [972] = 1,
    ACTIONS(204), 1,
      sym_times,
  [976] = 1,
    ACTIONS(206), 1,
      sym_number,
  [980] = 1,
    ACTIONS(208), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 63,
  [SMALL_STATE(5)] = 93,
  [SMALL_STATE(6)] = 121,
  [SMALL_STATE(7)] = 149,
  [SMALL_STATE(8)] = 177,
  [SMALL_STATE(9)] = 205,
  [SMALL_STATE(10)] = 233,
  [SMALL_STATE(11)] = 261,
  [SMALL_STATE(12)] = 289,
  [SMALL_STATE(13)] = 317,
  [SMALL_STATE(14)] = 345,
  [SMALL_STATE(15)] = 373,
  [SMALL_STATE(16)] = 392,
  [SMALL_STATE(17)] = 411,
  [SMALL_STATE(18)] = 439,
  [SMALL_STATE(19)] = 467,
  [SMALL_STATE(20)] = 495,
  [SMALL_STATE(21)] = 523,
  [SMALL_STATE(22)] = 539,
  [SMALL_STATE(23)] = 555,
  [SMALL_STATE(24)] = 571,
  [SMALL_STATE(25)] = 584,
  [SMALL_STATE(26)] = 597,
  [SMALL_STATE(27)] = 619,
  [SMALL_STATE(28)] = 629,
  [SMALL_STATE(29)] = 643,
  [SMALL_STATE(30)] = 653,
  [SMALL_STATE(31)] = 675,
  [SMALL_STATE(32)] = 685,
  [SMALL_STATE(33)] = 699,
  [SMALL_STATE(34)] = 709,
  [SMALL_STATE(35)] = 719,
  [SMALL_STATE(36)] = 729,
  [SMALL_STATE(37)] = 739,
  [SMALL_STATE(38)] = 749,
  [SMALL_STATE(39)] = 759,
  [SMALL_STATE(40)] = 769,
  [SMALL_STATE(41)] = 781,
  [SMALL_STATE(42)] = 795,
  [SMALL_STATE(43)] = 809,
  [SMALL_STATE(44)] = 823,
  [SMALL_STATE(45)] = 837,
  [SMALL_STATE(46)] = 845,
  [SMALL_STATE(47)] = 853,
  [SMALL_STATE(48)] = 861,
  [SMALL_STATE(49)] = 868,
  [SMALL_STATE(50)] = 875,
  [SMALL_STATE(51)] = 882,
  [SMALL_STATE(52)] = 892,
  [SMALL_STATE(53)] = 902,
  [SMALL_STATE(54)] = 907,
  [SMALL_STATE(55)] = 912,
  [SMALL_STATE(56)] = 919,
  [SMALL_STATE(57)] = 926,
  [SMALL_STATE(58)] = 933,
  [SMALL_STATE(59)] = 940,
  [SMALL_STATE(60)] = 947,
  [SMALL_STATE(61)] = 952,
  [SMALL_STATE(62)] = 959,
  [SMALL_STATE(63)] = 964,
  [SMALL_STATE(64)] = 968,
  [SMALL_STATE(65)] = 972,
  [SMALL_STATE(66)] = 976,
  [SMALL_STATE(67)] = 980,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mods, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mods_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mods_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mods_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mods_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 1, 0, 6),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 1, 0, 5),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 1, 0, 7),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 2, 0, 6),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 2, 0, 5),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 2, 0, 7),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 1, 0, 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rpe, 2, 0, 10),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weight, 2, 0, 11),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_percent, 2, 0, 12),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 3, 0, 15),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 2, 0, 8),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 4, 0, 22),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 5, 0, 24),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__weight_first, 2, 0, 11),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__mod, 1, 0, 6),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 2, 0, 9),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__percent_first, 2, 0, 12),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rest, 2, 0, 11),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 4, 0, 23),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 3, 0, 16),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rpe, 3, 0, 18),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__legacy_weight, 3, 0, 17),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weight, 3, 0, 19),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_percent, 3, 0, 20),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 4, 0, 1),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 3, 0, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__weight_first, 3, 0, 19),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__percent_first, 3, 0, 20),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rest_first, 2, 0, 11),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 4, 0, 3),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 5, 0, 14),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 3, 0, 4),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 6, 0, 21),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 4, 0, 13),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [208] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_workline(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "workline",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 3,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
