/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 51
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 22
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_SLASH = 2,
  anon_sym_COMMA = 3,
  sym_name = 4,
  aux_sym_group_token1 = 5,
  anon_sym_DASH = 6,
  aux_sym_target_token1 = 7,
  anon_sym_PLUS = 8,
  aux_sym_weight_token1 = 9,
  anon_sym_AT = 10,
  sym_ask_weight = 11,
  anon_sym_PERCENT = 12,
  aux_sym_rest_token1 = 13,
  aux_sym__num_imm_token1 = 14,
  sym_number = 15,
  sym_document = 16,
  sym_line = 17,
  sym_group = 18,
  sym_target = 19,
  sym_mods = 20,
  sym_weight = 21,
  sym_percent = 22,
  sym_rpe = 23,
  sym_rest = 24,
  sym__ask = 25,
  sym__num_imm = 26,
  aux_sym_document_repeat1 = 27,
  aux_sym_line_repeat1 = 28,
  aux_sym_mods_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_SLASH] = "/",
  [anon_sym_COMMA] = ",",
  [sym_name] = "name",
  [aux_sym_group_token1] = "group_token1",
  [anon_sym_DASH] = "-",
  [aux_sym_target_token1] = "unit",
  [anon_sym_PLUS] = "ask",
  [aux_sym_weight_token1] = "unit",
  [anon_sym_AT] = "@",
  [sym_ask_weight] = "ask_weight",
  [anon_sym_PERCENT] = "%",
  [aux_sym_rest_token1] = "unit",
  [aux_sym__num_imm_token1] = "number",
  [sym_number] = "number",
  [sym_document] = "document",
  [sym_line] = "line",
  [sym_group] = "group",
  [sym_target] = "target",
  [sym_mods] = "mods",
  [sym_weight] = "weight",
  [sym_percent] = "percent",
  [sym_rpe] = "rpe",
  [sym_rest] = "rest",
  [sym__ask] = "_ask",
  [sym__num_imm] = "_num_imm",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_line_repeat1] = "line_repeat1",
  [aux_sym_mods_repeat1] = "mods_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_name] = sym_name,
  [aux_sym_group_token1] = aux_sym_group_token1,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_target_token1] = aux_sym_target_token1,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [aux_sym_weight_token1] = aux_sym_target_token1,
  [anon_sym_AT] = anon_sym_AT,
  [sym_ask_weight] = sym_ask_weight,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_rest_token1] = aux_sym_target_token1,
  [aux_sym__num_imm_token1] = sym_number,
  [sym_number] = sym_number,
  [sym_document] = sym_document,
  [sym_line] = sym_line,
  [sym_group] = sym_group,
  [sym_target] = sym_target,
  [sym_mods] = sym_mods,
  [sym_weight] = sym_weight,
  [sym_percent] = sym_percent,
  [sym_rpe] = sym_rpe,
  [sym_rest] = sym_rest,
  [sym__ask] = sym__ask,
  [sym__num_imm] = sym__num_imm,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_line_repeat1] = aux_sym_line_repeat1,
  [aux_sym_mods_repeat1] = aux_sym_mods_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_group_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_target_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_weight_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_ask_weight] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_rest_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__num_imm_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_target] = {
    .visible = true,
    .named = true,
  },
  [sym_mods] = {
    .visible = true,
    .named = true,
  },
  [sym_weight] = {
    .visible = true,
    .named = true,
  },
  [sym_percent] = {
    .visible = true,
    .named = true,
  },
  [sym_rpe] = {
    .visible = true,
    .named = true,
  },
  [sym_rest] = {
    .visible = true,
    .named = true,
  },
  [sym__ask] = {
    .visible = false,
    .named = true,
  },
  [sym__num_imm] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mods_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_ask = 1,
  field_defaults = 2,
  field_max = 3,
  field_min = 4,
  field_name = 5,
  field_sets = 6,
  field_target = 7,
  field_unit = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_ask] = "ask",
  [field_defaults] = "defaults",
  [field_max] = "max",
  [field_min] = "min",
  [field_name] = "name",
  [field_sets] = "sets",
  [field_target] = "target",
  [field_unit] = "unit",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 1},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 1},
  [10] = {.index = 13, .length = 1},
  [11] = {.index = 14, .length = 2},
  [12] = {.index = 16, .length = 2},
  [13] = {.index = 18, .length = 3},
  [14] = {.index = 21, .length = 2},
  [15] = {.index = 23, .length = 2},
  [16] = {.index = 25, .length = 3},
  [17] = {.index = 28, .length = 2},
  [18] = {.index = 30, .length = 2},
  [19] = {.index = 32, .length = 3},
  [20] = {.index = 35, .length = 3},
  [21] = {.index = 38, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_min, 0},
  [2] =
    {field_sets, 0},
    {field_target, 2},
  [4] =
    {field_defaults, 2},
  [5] =
    {field_min, 0},
    {field_unit, 1},
  [7] =
    {field_ask, 1},
    {field_min, 0},
  [9] =
    {field_value, 1},
  [10] =
    {field_unit, 1},
    {field_value, 0},
  [12] =
    {field_value, 0},
  [13] =
    {field_defaults, 3},
  [14] =
    {field_defaults, 4},
    {field_name, 0},
  [16] =
    {field_max, 2},
    {field_min, 0},
  [18] =
    {field_ask, 2},
    {field_min, 0},
    {field_unit, 1},
  [21] =
    {field_unit, 2},
    {field_value, 1},
  [23] =
    {field_ask, 2},
    {field_value, 1},
  [25] =
    {field_ask, 2},
    {field_unit, 1},
    {field_value, 0},
  [28] =
    {field_ask, 2},
    {field_value, 0},
  [30] =
    {field_defaults, 5},
    {field_name, 0},
  [32] =
    {field_max, 2},
    {field_min, 0},
    {field_unit, 3},
  [35] =
    {field_ask, 3},
    {field_max, 2},
    {field_min, 0},
  [38] =
    {field_ask, 4},
    {field_max, 2},
    {field_min, 0},
    {field_unit, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '\n', 16,
        '%', 28,
        '+', 24,
        ',', 18,
        '-', 21,
        '/', 17,
        '?', 2,
        '@', 26,
        'K', 5,
        'k', 5,
        'L', 3,
        'l', 3,
        'M', 23,
        'm', 23,
        'S', 22,
        's', 22,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(12);
      if (lookahead == 'X' ||
          lookahead == 'x' ||
          lookahead == 0xd7) ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '%', 28,
        'K', 4,
        'k', 4,
        'L', 3,
        'l', 3,
        'M', 6,
        'm', 6,
        'S', 29,
        's', 29,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '+') ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(25);
      END_STATE();
    case 4:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(25);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(22);
      END_STATE();
    case 6:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 11:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '\n', 16,
        '+', 24,
        ',', 18,
        '-', 21,
        '/', 17,
        '?', 2,
        '@', 26,
        'K', 5,
        'k', 5,
        'L', 3,
        'l', 3,
        'M', 23,
        'm', 23,
        'S', 22,
        's', 22,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 12:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == ',') ADVANCE(18);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '?') ADVANCE(2);
      if (lookahead == '@') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(12);
      if (lookahead == 'X' ||
          lookahead == 'x' ||
          lookahead == 0xd7) ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 13:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == ',') ADVANCE(18);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '?') ADVANCE(2);
      if (lookahead == '@') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < '/' || '9' < lookahead)) ADVANCE(19);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_group_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_target_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_target_token1);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_weight_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_ask_weight);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_rest_token1);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__num_imm_token1);
      if (lookahead == '.') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__num_imm_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 11},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 14},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 14},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 14},
  [45] = {.lex_state = 14},
  [46] = {.lex_state = 14},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_group_token1] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [aux_sym_target_token1] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [aux_sym_weight_token1] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_ask_weight] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [aux_sym_rest_token1] = ACTIONS(1),
    [aux_sym__num_imm_token1] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(49),
    [sym_line] = STATE(42),
    [sym_group] = STATE(30),
    [aux_sym_document_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_name] = ACTIONS(7),
    [sym_number] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_ask_weight,
    ACTIONS(17), 1,
      sym_number,
    STATE(33), 1,
      sym_mods,
    ACTIONS(11), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
    STATE(3), 5,
      sym_weight,
      sym_percent,
      sym_rpe,
      sym_rest,
      aux_sym_mods_repeat1,
  [26] = 5,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_ask_weight,
    ACTIONS(19), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
    STATE(4), 5,
      sym_weight,
      sym_percent,
      sym_rpe,
      sym_rest,
      aux_sym_mods_repeat1,
  [49] = 5,
    ACTIONS(25), 1,
      anon_sym_AT,
    ACTIONS(28), 1,
      sym_ask_weight,
    ACTIONS(31), 1,
      sym_number,
    ACTIONS(23), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
    STATE(4), 5,
      sym_weight,
      sym_percent,
      sym_rpe,
      sym_rest,
      aux_sym_mods_repeat1,
  [72] = 4,
    ACTIONS(36), 1,
      anon_sym_DASH,
    ACTIONS(38), 1,
      aux_sym_target_token1,
    ACTIONS(40), 1,
      anon_sym_PLUS,
    ACTIONS(34), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [91] = 4,
    ACTIONS(44), 1,
      anon_sym_PLUS,
    ACTIONS(46), 1,
      aux_sym_weight_token1,
    STATE(22), 1,
      sym__ask,
    ACTIONS(42), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [110] = 5,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_ask_weight,
    ACTIONS(17), 1,
      sym_number,
    STATE(38), 1,
      sym_mods,
    STATE(3), 5,
      sym_weight,
      sym_percent,
      sym_rpe,
      sym_rest,
      aux_sym_mods_repeat1,
  [130] = 5,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_ask_weight,
    ACTIONS(17), 1,
      sym_number,
    STATE(40), 1,
      sym_mods,
    STATE(3), 5,
      sym_weight,
      sym_percent,
      sym_rpe,
      sym_rest,
      aux_sym_mods_repeat1,
  [150] = 5,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_ask_weight,
    ACTIONS(17), 1,
      sym_number,
    STATE(39), 1,
      sym_mods,
    STATE(3), 5,
      sym_weight,
      sym_percent,
      sym_rpe,
      sym_rest,
      aux_sym_mods_repeat1,
  [170] = 3,
    ACTIONS(50), 1,
      anon_sym_PLUS,
    STATE(23), 1,
      sym__ask,
    ACTIONS(48), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [186] = 3,
    ACTIONS(54), 1,
      anon_sym_PLUS,
    STATE(24), 1,
      sym__ask,
    ACTIONS(52), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [202] = 3,
    ACTIONS(58), 1,
      aux_sym_target_token1,
    ACTIONS(60), 1,
      anon_sym_PLUS,
    ACTIONS(56), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [218] = 5,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_ask_weight,
    ACTIONS(17), 1,
      sym_number,
    STATE(41), 1,
      sym_mods,
    STATE(3), 5,
      sym_weight,
      sym_percent,
      sym_rpe,
      sym_rest,
      aux_sym_mods_repeat1,
  [238] = 2,
    ACTIONS(64), 1,
      anon_sym_PLUS,
    ACTIONS(62), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [251] = 2,
    ACTIONS(68), 1,
      anon_sym_PLUS,
    ACTIONS(66), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [264] = 1,
    ACTIONS(70), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [274] = 1,
    ACTIONS(72), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [284] = 7,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 1,
      anon_sym_LF,
    ACTIONS(79), 1,
      sym_name,
    ACTIONS(82), 1,
      sym_number,
    STATE(18), 1,
      aux_sym_document_repeat1,
    STATE(30), 1,
      sym_group,
    STATE(50), 1,
      sym_line,
  [306] = 1,
    ACTIONS(85), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [316] = 1,
    ACTIONS(87), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [326] = 7,
    ACTIONS(7), 1,
      sym_name,
    ACTIONS(9), 1,
      sym_number,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    ACTIONS(91), 1,
      anon_sym_LF,
    STATE(18), 1,
      aux_sym_document_repeat1,
    STATE(30), 1,
      sym_group,
    STATE(37), 1,
      sym_line,
  [348] = 1,
    ACTIONS(93), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [358] = 1,
    ACTIONS(95), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [368] = 1,
    ACTIONS(97), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [378] = 1,
    ACTIONS(99), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [388] = 1,
    ACTIONS(101), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      sym_number,
  [398] = 4,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    STATE(31), 1,
      aux_sym_line_repeat1,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [412] = 4,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    ACTIONS(111), 1,
      anon_sym_SLASH,
    STATE(31), 1,
      aux_sym_line_repeat1,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [426] = 4,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    ACTIONS(115), 1,
      anon_sym_SLASH,
    STATE(27), 1,
      aux_sym_line_repeat1,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [440] = 4,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    ACTIONS(119), 1,
      anon_sym_SLASH,
    STATE(28), 1,
      aux_sym_line_repeat1,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [454] = 3,
    ACTIONS(123), 1,
      anon_sym_COMMA,
    STATE(31), 1,
      aux_sym_line_repeat1,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
  [466] = 1,
    ACTIONS(74), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_name,
      sym_number,
  [473] = 1,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
  [480] = 1,
    ACTIONS(121), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
  [487] = 3,
    ACTIONS(128), 1,
      aux_sym_weight_token1,
    ACTIONS(130), 1,
      anon_sym_PERCENT,
    ACTIONS(132), 1,
      aux_sym_rest_token1,
  [497] = 2,
    ACTIONS(134), 1,
      sym_number,
    STATE(2), 1,
      sym_target,
  [504] = 2,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    ACTIONS(138), 1,
      anon_sym_LF,
  [511] = 1,
    ACTIONS(140), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [516] = 1,
    ACTIONS(142), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [521] = 1,
    ACTIONS(144), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [526] = 1,
    ACTIONS(146), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [531] = 2,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    ACTIONS(138), 1,
      anon_sym_LF,
  [538] = 2,
    ACTIONS(148), 1,
      aux_sym__num_imm_token1,
    STATE(6), 1,
      sym__num_imm,
  [545] = 2,
    ACTIONS(9), 1,
      sym_number,
    STATE(34), 1,
      sym_group,
  [552] = 2,
    ACTIONS(9), 1,
      sym_number,
    STATE(29), 1,
      sym_group,
  [559] = 1,
    ACTIONS(150), 1,
      sym_number,
  [563] = 1,
    ACTIONS(152), 1,
      anon_sym_SLASH,
  [567] = 1,
    ACTIONS(154), 1,
      aux_sym_group_token1,
  [571] = 1,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
  [575] = 1,
    ACTIONS(138), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 49,
  [SMALL_STATE(5)] = 72,
  [SMALL_STATE(6)] = 91,
  [SMALL_STATE(7)] = 110,
  [SMALL_STATE(8)] = 130,
  [SMALL_STATE(9)] = 150,
  [SMALL_STATE(10)] = 170,
  [SMALL_STATE(11)] = 186,
  [SMALL_STATE(12)] = 202,
  [SMALL_STATE(13)] = 218,
  [SMALL_STATE(14)] = 238,
  [SMALL_STATE(15)] = 251,
  [SMALL_STATE(16)] = 264,
  [SMALL_STATE(17)] = 274,
  [SMALL_STATE(18)] = 284,
  [SMALL_STATE(19)] = 306,
  [SMALL_STATE(20)] = 316,
  [SMALL_STATE(21)] = 326,
  [SMALL_STATE(22)] = 348,
  [SMALL_STATE(23)] = 358,
  [SMALL_STATE(24)] = 368,
  [SMALL_STATE(25)] = 378,
  [SMALL_STATE(26)] = 388,
  [SMALL_STATE(27)] = 398,
  [SMALL_STATE(28)] = 412,
  [SMALL_STATE(29)] = 426,
  [SMALL_STATE(30)] = 440,
  [SMALL_STATE(31)] = 454,
  [SMALL_STATE(32)] = 466,
  [SMALL_STATE(33)] = 473,
  [SMALL_STATE(34)] = 480,
  [SMALL_STATE(35)] = 487,
  [SMALL_STATE(36)] = 497,
  [SMALL_STATE(37)] = 504,
  [SMALL_STATE(38)] = 511,
  [SMALL_STATE(39)] = 516,
  [SMALL_STATE(40)] = 521,
  [SMALL_STATE(41)] = 526,
  [SMALL_STATE(42)] = 531,
  [SMALL_STATE(43)] = 538,
  [SMALL_STATE(44)] = 545,
  [SMALL_STATE(45)] = 552,
  [SMALL_STATE(46)] = 559,
  [SMALL_STATE(47)] = 563,
  [SMALL_STATE(48)] = 567,
  [SMALL_STATE(49)] = 571,
  [SMALL_STATE(50)] = 575,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mods, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mods_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mods_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mods_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mods_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 1, 0, 2),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rpe, 2, 0, 7),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weight, 2, 0, 8),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_percent, 2, 0, 9),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 3, 0, 12),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 2, 0, 5),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 4, 0, 19),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 5, 0, 21),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 2, 0, 6),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rest, 2, 0, 8),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 3, 0, 13),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rpe, 3, 0, 15),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weight, 3, 0, 16),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_percent, 3, 0, 17),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weight, 3, 0, 14),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 4, 0, 20),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 4, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 3, 0, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 4, 0, 3),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 4, 0, 10),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 3, 0, 4),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 5, 0, 11),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 6, 0, 18),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [156] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_workline(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "workline",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
