/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 73
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 28
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_SLASH = 2,
  anon_sym_COMMA = 3,
  sym_name = 4,
  sym_times = 5,
  anon_sym_PIPE = 6,
  anon_sym_PLUS = 7,
  anon_sym_DASH = 8,
  aux_sym_step_token1 = 9,
  anon_sym_QMARK_PLUS = 10,
  aux_sym_weight_token1 = 11,
  anon_sym_AT = 12,
  sym_ask_weight = 13,
  anon_sym_PERCENT = 14,
  aux_sym_rest_token1 = 15,
  aux_sym__gap_num_token1 = 16,
  aux_sym__num_imm_token1 = 17,
  sym_number = 18,
  sym_document = 19,
  sym_line = 20,
  sym_group = 21,
  sym_target = 22,
  sym_step = 23,
  sym_mods = 24,
  sym_defaults = 25,
  sym__mod = 26,
  sym_weight = 27,
  sym__weight_first = 28,
  sym__legacy_weight = 29,
  sym_percent = 30,
  sym__percent_first = 31,
  sym_rest = 32,
  sym__rest_first = 33,
  sym_rpe = 34,
  sym__gap_num = 35,
  sym__ask = 36,
  sym__num_imm = 37,
  aux_sym_document_repeat1 = 38,
  aux_sym_line_repeat1 = 39,
  aux_sym_target_repeat1 = 40,
  aux_sym_mods_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_SLASH] = "/",
  [anon_sym_COMMA] = ",",
  [sym_name] = "name",
  [sym_times] = "times",
  [anon_sym_PIPE] = "|",
  [anon_sym_PLUS] = "ask",
  [anon_sym_DASH] = "-",
  [aux_sym_step_token1] = "unit",
  [anon_sym_QMARK_PLUS] = "ask_weight",
  [aux_sym_weight_token1] = "unit",
  [anon_sym_AT] = "@",
  [sym_ask_weight] = "ask_weight",
  [anon_sym_PERCENT] = "%",
  [aux_sym_rest_token1] = "unit",
  [aux_sym__gap_num_token1] = "number",
  [aux_sym__num_imm_token1] = "number",
  [sym_number] = "number",
  [sym_document] = "document",
  [sym_line] = "line",
  [sym_group] = "group",
  [sym_target] = "target",
  [sym_step] = "step",
  [sym_mods] = "mods",
  [sym_defaults] = "defaults",
  [sym__mod] = "_mod",
  [sym_weight] = "weight",
  [sym__weight_first] = "weight",
  [sym__legacy_weight] = "weight",
  [sym_percent] = "percent",
  [sym__percent_first] = "percent",
  [sym_rest] = "rest",
  [sym__rest_first] = "rest",
  [sym_rpe] = "rpe",
  [sym__gap_num] = "_gap_num",
  [sym__ask] = "_ask",
  [sym__num_imm] = "_num_imm",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_line_repeat1] = "line_repeat1",
  [aux_sym_target_repeat1] = "target_repeat1",
  [aux_sym_mods_repeat1] = "mods_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_name] = sym_name,
  [sym_times] = sym_times,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_step_token1] = aux_sym_step_token1,
  [anon_sym_QMARK_PLUS] = sym_ask_weight,
  [aux_sym_weight_token1] = aux_sym_step_token1,
  [anon_sym_AT] = anon_sym_AT,
  [sym_ask_weight] = sym_ask_weight,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_rest_token1] = aux_sym_step_token1,
  [aux_sym__gap_num_token1] = sym_number,
  [aux_sym__num_imm_token1] = sym_number,
  [sym_number] = sym_number,
  [sym_document] = sym_document,
  [sym_line] = sym_line,
  [sym_group] = sym_group,
  [sym_target] = sym_target,
  [sym_step] = sym_step,
  [sym_mods] = sym_mods,
  [sym_defaults] = sym_defaults,
  [sym__mod] = sym__mod,
  [sym_weight] = sym_weight,
  [sym__weight_first] = sym_weight,
  [sym__legacy_weight] = sym_weight,
  [sym_percent] = sym_percent,
  [sym__percent_first] = sym_percent,
  [sym_rest] = sym_rest,
  [sym__rest_first] = sym_rest,
  [sym_rpe] = sym_rpe,
  [sym__gap_num] = sym__gap_num,
  [sym__ask] = sym__ask,
  [sym__num_imm] = sym__num_imm,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_line_repeat1] = aux_sym_line_repeat1,
  [aux_sym_target_repeat1] = aux_sym_target_repeat1,
  [aux_sym_mods_repeat1] = aux_sym_mods_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_times] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_step_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_QMARK_PLUS] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_weight_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_ask_weight] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_rest_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__gap_num_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__num_imm_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_target] = {
    .visible = true,
    .named = true,
  },
  [sym_step] = {
    .visible = true,
    .named = true,
  },
  [sym_mods] = {
    .visible = true,
    .named = true,
  },
  [sym_defaults] = {
    .visible = true,
    .named = true,
  },
  [sym__mod] = {
    .visible = false,
    .named = true,
  },
  [sym_weight] = {
    .visible = true,
    .named = true,
  },
  [sym__weight_first] = {
    .visible = true,
    .named = true,
  },
  [sym__legacy_weight] = {
    .visible = true,
    .named = true,
  },
  [sym_percent] = {
    .visible = true,
    .named = true,
  },
  [sym__percent_first] = {
    .visible = true,
    .named = true,
  },
  [sym_rest] = {
    .visible = true,
    .named = true,
  },
  [sym__rest_first] = {
    .visible = true,
    .named = true,
  },
  [sym_rpe] = {
    .visible = true,
    .named = true,
  },
  [sym__gap_num] = {
    .visible = false,
    .named = true,
  },
  [sym__ask] = {
    .visible = false,
    .named = true,
  },
  [sym__num_imm] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_target_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mods_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_ask = 1,
  field_defaults = 2,
  field_max = 3,
  field_min = 4,
  field_name = 5,
  field_sets = 6,
  field_step = 7,
  field_target = 8,
  field_unit = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_ask] = "ask",
  [field_defaults] = "defaults",
  [field_max] = "max",
  [field_min] = "min",
  [field_name] = "name",
  [field_sets] = "sets",
  [field_step] = "step",
  [field_target] = "target",
  [field_unit] = "unit",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 1},
  [12] = {.index = 17, .length = 3},
  [13] = {.index = 20, .length = 2},
  [14] = {.index = 22, .length = 1},
  [15] = {.index = 23, .length = 2},
  [16] = {.index = 25, .length = 1},
  [17] = {.index = 26, .length = 1},
  [18] = {.index = 27, .length = 3},
  [19] = {.index = 30, .length = 2},
  [20] = {.index = 32, .length = 3},
  [21] = {.index = 35, .length = 1},
  [22] = {.index = 36, .length = 2},
  [23] = {.index = 38, .length = 2},
  [24] = {.index = 40, .length = 3},
  [25] = {.index = 43, .length = 2},
  [26] = {.index = 45, .length = 2},
  [27] = {.index = 47, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_min, 0},
  [1] =
    {field_target, 0},
  [2] =
    {field_step, 0},
  [3] =
    {field_min, 0},
    {field_unit, 1},
  [5] =
    {field_unit, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [7] =
    {field_ask, 1},
    {field_step, 0},
  [9] =
    {field_step, 0},
    {field_step, 1, .inherited = true},
  [11] =
    {field_name, 0},
  [12] =
    {field_sets, 0},
    {field_target, 2},
  [14] =
    {field_max, 2},
    {field_min, 0},
  [16] =
    {field_defaults, 2},
  [17] =
    {field_ask, 0, .inherited = true},
    {field_unit, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [20] =
    {field_ask, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [22] =
    {field_value, 1},
  [23] =
    {field_unit, 1},
    {field_value, 0},
  [25] =
    {field_value, 0},
  [26] =
    {field_step, 1},
  [27] =
    {field_ask, 2},
    {field_step, 0},
    {field_step, 1, .inherited = true},
  [30] =
    {field_step, 0, .inherited = true},
    {field_step, 1, .inherited = true},
  [32] =
    {field_max, 2},
    {field_min, 0},
    {field_unit, 3},
  [35] =
    {field_defaults, 3},
  [36] =
    {field_unit, 2},
    {field_value, 1},
  [38] =
    {field_ask, 2},
    {field_value, 1},
  [40] =
    {field_ask, 2},
    {field_unit, 1},
    {field_value, 0},
  [43] =
    {field_ask, 2},
    {field_value, 0},
  [45] =
    {field_defaults, 4},
    {field_name, 0},
  [47] =
    {field_defaults, 5},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(17);
      if (lookahead == '%') ADVANCE(37);
      if (lookahead == '\'') ADVANCE(31);
      if (lookahead == '+') ADVANCE(28);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '?') ADVANCE(6);
      if (lookahead == '@') ADVANCE(35);
      if (lookahead == '|') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead == 'K' ||
          lookahead == 'k') ADVANCE(11);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(9);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(32);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(30);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(30);
      if (lookahead == 'X' ||
          lookahead == 'x' ||
          lookahead == 0xd7) ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(2);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead == '@') ADVANCE(35);
      if (lookahead == '|') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead == 'X' ||
          lookahead == 'x' ||
          lookahead == 0xd7) ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(2);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '@') ADVANCE(35);
      if (lookahead == '|') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead == 'X' ||
          lookahead == 'x' ||
          lookahead == 0xd7) ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(3);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '?') ADVANCE(6);
      if (lookahead == '@') ADVANCE(35);
      if (lookahead == '|') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead == 'X' ||
          lookahead == 'x' ||
          lookahead == 0xd7) ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(3);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '?') ADVANCE(6);
      if (lookahead == '@') ADVANCE(35);
      if (lookahead == '|') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead == 'X' ||
          lookahead == 'x' ||
          lookahead == 0xd7) ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '%', 37,
        '\'', 39,
        '?', 6,
        '@', 35,
        'K', 10,
        'k', 10,
        'L', 9,
        'l', 9,
        'M', 40,
        'm', 40,
        'S', 38,
        's', 38,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 6:
      if (lookahead == '+') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == '+') ADVANCE(36);
      END_STATE();
    case 8:
      if (lookahead == '?') ADVANCE(6);
      if (lookahead == '@') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 9:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(34);
      END_STATE();
    case 10:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(34);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(30);
      END_STATE();
    case 12:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 13:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 17:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(17);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '?') ADVANCE(6);
      if (lookahead == '@') ADVANCE(35);
      if (lookahead == '|') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead == 'X' ||
          lookahead == 'x' ||
          lookahead == 0xd7) ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 18:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(19);
      if (lookahead == '\'') ADVANCE(31);
      if (lookahead == '+') ADVANCE(28);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '@') ADVANCE(35);
      if (lookahead == '|') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead == 'K' ||
          lookahead == 'k') ADVANCE(11);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(9);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(32);
      if (lookahead == 'X' ||
          lookahead == 'x' ||
          lookahead == 0xd7) ADVANCE(26);
      if (lookahead == 'R' ||
          lookahead == 'S' ||
          lookahead == 'r' ||
          lookahead == 's') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 19:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') SKIP(19);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '@') ADVANCE(35);
      if (lookahead == '|') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead == 'X' ||
          lookahead == 'x' ||
          lookahead == 0xd7) ADVANCE(26);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < '/' || '9' < lookahead)) ADVANCE(25);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_times);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_step_token1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_step_token1);
      if (lookahead == '\'') ADVANCE(30);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_step_token1);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_QMARK_PLUS);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_weight_token1);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_ask_weight);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_rest_token1);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_rest_token1);
      if (lookahead == '\'') ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_rest_token1);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym__gap_num_token1);
      if (lookahead == '.') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__gap_num_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym__num_imm_token1);
      if (lookahead == '.') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym__num_imm_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 18},
  [5] = {.lex_state = 18},
  [6] = {.lex_state = 18},
  [7] = {.lex_state = 18},
  [8] = {.lex_state = 18},
  [9] = {.lex_state = 18},
  [10] = {.lex_state = 18},
  [11] = {.lex_state = 18},
  [12] = {.lex_state = 18},
  [13] = {.lex_state = 18},
  [14] = {.lex_state = 18},
  [15] = {.lex_state = 18},
  [16] = {.lex_state = 18},
  [17] = {.lex_state = 18},
  [18] = {.lex_state = 18},
  [19] = {.lex_state = 18},
  [20] = {.lex_state = 18},
  [21] = {.lex_state = 18},
  [22] = {.lex_state = 18},
  [23] = {.lex_state = 18},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 20},
  [26] = {.lex_state = 20},
  [27] = {.lex_state = 18},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 18},
  [31] = {.lex_state = 18},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 18},
  [34] = {.lex_state = 18},
  [35] = {.lex_state = 18},
  [36] = {.lex_state = 18},
  [37] = {.lex_state = 18},
  [38] = {.lex_state = 18},
  [39] = {.lex_state = 18},
  [40] = {.lex_state = 18},
  [41] = {.lex_state = 18},
  [42] = {.lex_state = 18},
  [43] = {.lex_state = 18},
  [44] = {.lex_state = 18},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 18},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 18},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 20},
  [54] = {.lex_state = 20},
  [55] = {.lex_state = 20},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 5},
  [60] = {.lex_state = 20},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 20},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 18},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 20},
  [72] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_times] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [aux_sym_step_token1] = ACTIONS(1),
    [anon_sym_QMARK_PLUS] = ACTIONS(1),
    [aux_sym_weight_token1] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_ask_weight] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [aux_sym_rest_token1] = ACTIONS(1),
    [aux_sym__gap_num_token1] = ACTIONS(1),
    [aux_sym__num_imm_token1] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(72),
    [sym_line] = STATE(63),
    [sym_group] = STATE(48),
    [sym_target] = STATE(3),
    [sym_step] = STATE(18),
    [aux_sym_document_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_name] = ACTIONS(7),
    [sym_number] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_ask_weight,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    STATE(41), 1,
      sym__legacy_weight,
    STATE(57), 1,
      sym_mods,
    STATE(59), 1,
      sym__gap_num,
    ACTIONS(11), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
    STATE(4), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [33] = 8,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_ask_weight,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    STATE(41), 1,
      sym__legacy_weight,
    STATE(56), 1,
      sym_mods,
    STATE(59), 1,
      sym__gap_num,
    ACTIONS(19), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
    STATE(4), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [66] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(23), 1,
      sym_ask_weight,
    STATE(41), 1,
      sym__legacy_weight,
    STATE(59), 1,
      sym__gap_num,
    ACTIONS(21), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
    STATE(5), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [96] = 7,
    ACTIONS(27), 1,
      anon_sym_AT,
    ACTIONS(30), 1,
      sym_ask_weight,
    ACTIONS(33), 1,
      aux_sym__gap_num_token1,
    STATE(41), 1,
      sym__legacy_weight,
    STATE(59), 1,
      sym__gap_num,
    ACTIONS(25), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
    STATE(5), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [126] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(38), 1,
      sym_ask_weight,
    STATE(41), 1,
      sym__legacy_weight,
    STATE(59), 1,
      sym__gap_num,
    ACTIONS(36), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(12), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [154] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(42), 1,
      sym_ask_weight,
    STATE(41), 1,
      sym__legacy_weight,
    STATE(59), 1,
      sym__gap_num,
    ACTIONS(40), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(9), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [182] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(46), 1,
      sym_ask_weight,
    STATE(41), 1,
      sym__legacy_weight,
    STATE(59), 1,
      sym__gap_num,
    ACTIONS(44), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(13), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [210] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(23), 1,
      sym_ask_weight,
    STATE(41), 1,
      sym__legacy_weight,
    STATE(59), 1,
      sym__gap_num,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(5), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [238] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(52), 1,
      sym_ask_weight,
    STATE(41), 1,
      sym__legacy_weight,
    STATE(59), 1,
      sym__gap_num,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(14), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [266] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(54), 1,
      sym_ask_weight,
    STATE(41), 1,
      sym__legacy_weight,
    STATE(59), 1,
      sym__gap_num,
    ACTIONS(44), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(15), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [294] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(23), 1,
      sym_ask_weight,
    STATE(41), 1,
      sym__legacy_weight,
    STATE(59), 1,
      sym__gap_num,
    ACTIONS(56), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(5), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [322] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(23), 1,
      sym_ask_weight,
    STATE(41), 1,
      sym__legacy_weight,
    STATE(59), 1,
      sym__gap_num,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(5), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [350] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(23), 1,
      sym_ask_weight,
    STATE(41), 1,
      sym__legacy_weight,
    STATE(59), 1,
      sym__gap_num,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(5), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [378] = 7,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      aux_sym__gap_num_token1,
    ACTIONS(23), 1,
      sym_ask_weight,
    STATE(41), 1,
      sym__legacy_weight,
    STATE(59), 1,
      sym__gap_num,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(5), 6,
      sym__mod,
      sym_weight,
      sym_percent,
      sym_rest,
      sym_rpe,
      aux_sym_mods_repeat1,
  [406] = 4,
    ACTIONS(64), 1,
      sym_times,
    ACTIONS(66), 1,
      anon_sym_DASH,
    ACTIONS(68), 1,
      aux_sym_step_token1,
    ACTIONS(62), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [427] = 3,
    ACTIONS(66), 1,
      anon_sym_DASH,
    ACTIONS(68), 1,
      aux_sym_step_token1,
    ACTIONS(62), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [445] = 4,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    ACTIONS(74), 1,
      anon_sym_PLUS,
    STATE(19), 1,
      aux_sym_target_repeat1,
    ACTIONS(70), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [464] = 4,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    ACTIONS(78), 1,
      anon_sym_PLUS,
    STATE(21), 1,
      aux_sym_target_repeat1,
    ACTIONS(76), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [483] = 2,
    ACTIONS(82), 1,
      aux_sym_step_token1,
    ACTIONS(80), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [498] = 3,
    ACTIONS(86), 1,
      anon_sym_PIPE,
    STATE(21), 1,
      aux_sym_target_repeat1,
    ACTIONS(84), 8,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [515] = 4,
    ACTIONS(91), 1,
      anon_sym_PLUS,
    ACTIONS(93), 1,
      aux_sym_weight_token1,
    STATE(40), 1,
      sym__ask,
    ACTIONS(89), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [534] = 3,
    ACTIONS(97), 1,
      anon_sym_PLUS,
    STATE(42), 1,
      sym__ask,
    ACTIONS(95), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [550] = 9,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(99), 1,
      anon_sym_QMARK_PLUS,
    ACTIONS(101), 1,
      sym_number,
    STATE(6), 1,
      sym_rpe,
    STATE(7), 1,
      sym__weight_first,
    STATE(8), 1,
      sym__legacy_weight,
    STATE(10), 1,
      sym__percent_first,
    STATE(11), 1,
      sym__rest_first,
    STATE(68), 1,
      sym_defaults,
  [578] = 9,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 1,
      anon_sym_LF,
    ACTIONS(108), 1,
      sym_name,
    ACTIONS(111), 1,
      sym_number,
    STATE(3), 1,
      sym_target,
    STATE(18), 1,
      sym_step,
    STATE(25), 1,
      aux_sym_document_repeat1,
    STATE(48), 1,
      sym_group,
    STATE(69), 1,
      sym_line,
  [606] = 9,
    ACTIONS(7), 1,
      sym_name,
    ACTIONS(9), 1,
      sym_number,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 1,
      anon_sym_LF,
    STATE(3), 1,
      sym_target,
    STATE(18), 1,
      sym_step,
    STATE(25), 1,
      aux_sym_document_repeat1,
    STATE(48), 1,
      sym_group,
    STATE(65), 1,
      sym_line,
  [634] = 1,
    ACTIONS(118), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [646] = 9,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(99), 1,
      anon_sym_QMARK_PLUS,
    ACTIONS(101), 1,
      sym_number,
    STATE(6), 1,
      sym_rpe,
    STATE(7), 1,
      sym__weight_first,
    STATE(8), 1,
      sym__legacy_weight,
    STATE(10), 1,
      sym__percent_first,
    STATE(11), 1,
      sym__rest_first,
    STATE(61), 1,
      sym_defaults,
  [674] = 9,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(99), 1,
      anon_sym_QMARK_PLUS,
    ACTIONS(101), 1,
      sym_number,
    STATE(6), 1,
      sym_rpe,
    STATE(7), 1,
      sym__weight_first,
    STATE(8), 1,
      sym__legacy_weight,
    STATE(10), 1,
      sym__percent_first,
    STATE(11), 1,
      sym__rest_first,
    STATE(64), 1,
      sym_defaults,
  [702] = 3,
    ACTIONS(122), 1,
      anon_sym_PLUS,
    STATE(43), 1,
      sym__ask,
    ACTIONS(120), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [718] = 1,
    ACTIONS(124), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [730] = 9,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(99), 1,
      anon_sym_QMARK_PLUS,
    ACTIONS(101), 1,
      sym_number,
    STATE(6), 1,
      sym_rpe,
    STATE(7), 1,
      sym__weight_first,
    STATE(8), 1,
      sym__legacy_weight,
    STATE(10), 1,
      sym__percent_first,
    STATE(11), 1,
      sym__rest_first,
    STATE(67), 1,
      sym_defaults,
  [758] = 1,
    ACTIONS(126), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_PLUS,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [770] = 1,
    ACTIONS(128), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [780] = 1,
    ACTIONS(130), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [790] = 1,
    ACTIONS(132), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [800] = 3,
    ACTIONS(136), 1,
      anon_sym_PLUS,
    STATE(51), 1,
      sym__ask,
    ACTIONS(134), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [814] = 1,
    ACTIONS(138), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [824] = 3,
    ACTIONS(142), 1,
      anon_sym_PLUS,
    STATE(44), 1,
      sym__ask,
    ACTIONS(140), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [838] = 1,
    ACTIONS(144), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [848] = 1,
    ACTIONS(146), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [858] = 1,
    ACTIONS(148), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [868] = 1,
    ACTIONS(150), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [878] = 1,
    ACTIONS(152), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [886] = 3,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_line_repeat1,
    ACTIONS(154), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
  [898] = 4,
    ACTIONS(161), 1,
      anon_sym_SLASH,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_line_repeat1,
    ACTIONS(159), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [912] = 4,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    STATE(50), 1,
      aux_sym_line_repeat1,
    ACTIONS(165), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [926] = 4,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    ACTIONS(171), 1,
      anon_sym_SLASH,
    STATE(46), 1,
      aux_sym_line_repeat1,
    ACTIONS(169), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [940] = 1,
    ACTIONS(173), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [948] = 4,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_SLASH,
    STATE(45), 1,
      aux_sym_line_repeat1,
    ACTIONS(175), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [962] = 1,
    ACTIONS(179), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_AT,
      sym_ask_weight,
      aux_sym__gap_num_token1,
  [970] = 1,
    ACTIONS(154), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
  [977] = 4,
    ACTIONS(9), 1,
      sym_number,
    STATE(3), 1,
      sym_target,
    STATE(18), 1,
      sym_step,
    STATE(52), 1,
      sym_group,
  [990] = 1,
    ACTIONS(103), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_name,
      sym_number,
  [997] = 4,
    ACTIONS(9), 1,
      sym_number,
    STATE(3), 1,
      sym_target,
    STATE(18), 1,
      sym_step,
    STATE(47), 1,
      sym_group,
  [1010] = 1,
    ACTIONS(181), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
  [1017] = 1,
    ACTIONS(183), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SLASH,
      anon_sym_COMMA,
  [1024] = 3,
    ACTIONS(185), 1,
      aux_sym_weight_token1,
    ACTIONS(187), 1,
      anon_sym_PERCENT,
    ACTIONS(189), 1,
      aux_sym_rest_token1,
  [1034] = 3,
    ACTIONS(191), 1,
      aux_sym_weight_token1,
    ACTIONS(193), 1,
      anon_sym_PERCENT,
    ACTIONS(195), 1,
      aux_sym_rest_token1,
  [1044] = 3,
    ACTIONS(197), 1,
      sym_number,
    STATE(2), 1,
      sym_target,
    STATE(18), 1,
      sym_step,
  [1054] = 1,
    ACTIONS(199), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1059] = 2,
    ACTIONS(197), 1,
      sym_number,
    STATE(31), 1,
      sym_step,
  [1066] = 2,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
    ACTIONS(201), 1,
      anon_sym_LF,
  [1073] = 1,
    ACTIONS(203), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1078] = 2,
    ACTIONS(201), 1,
      anon_sym_LF,
    ACTIONS(205), 1,
      ts_builtin_sym_end,
  [1085] = 2,
    ACTIONS(207), 1,
      aux_sym__num_imm_token1,
    STATE(22), 1,
      sym__num_imm,
  [1092] = 1,
    ACTIONS(209), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1097] = 1,
    ACTIONS(211), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1102] = 1,
    ACTIONS(201), 1,
      anon_sym_LF,
  [1106] = 1,
    ACTIONS(213), 1,
      anon_sym_SLASH,
  [1110] = 1,
    ACTIONS(215), 1,
      sym_number,
  [1114] = 1,
    ACTIONS(217), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 126,
  [SMALL_STATE(7)] = 154,
  [SMALL_STATE(8)] = 182,
  [SMALL_STATE(9)] = 210,
  [SMALL_STATE(10)] = 238,
  [SMALL_STATE(11)] = 266,
  [SMALL_STATE(12)] = 294,
  [SMALL_STATE(13)] = 322,
  [SMALL_STATE(14)] = 350,
  [SMALL_STATE(15)] = 378,
  [SMALL_STATE(16)] = 406,
  [SMALL_STATE(17)] = 427,
  [SMALL_STATE(18)] = 445,
  [SMALL_STATE(19)] = 464,
  [SMALL_STATE(20)] = 483,
  [SMALL_STATE(21)] = 498,
  [SMALL_STATE(22)] = 515,
  [SMALL_STATE(23)] = 534,
  [SMALL_STATE(24)] = 550,
  [SMALL_STATE(25)] = 578,
  [SMALL_STATE(26)] = 606,
  [SMALL_STATE(27)] = 634,
  [SMALL_STATE(28)] = 646,
  [SMALL_STATE(29)] = 674,
  [SMALL_STATE(30)] = 702,
  [SMALL_STATE(31)] = 718,
  [SMALL_STATE(32)] = 730,
  [SMALL_STATE(33)] = 758,
  [SMALL_STATE(34)] = 770,
  [SMALL_STATE(35)] = 780,
  [SMALL_STATE(36)] = 790,
  [SMALL_STATE(37)] = 800,
  [SMALL_STATE(38)] = 814,
  [SMALL_STATE(39)] = 824,
  [SMALL_STATE(40)] = 838,
  [SMALL_STATE(41)] = 848,
  [SMALL_STATE(42)] = 858,
  [SMALL_STATE(43)] = 868,
  [SMALL_STATE(44)] = 878,
  [SMALL_STATE(45)] = 886,
  [SMALL_STATE(46)] = 898,
  [SMALL_STATE(47)] = 912,
  [SMALL_STATE(48)] = 926,
  [SMALL_STATE(49)] = 940,
  [SMALL_STATE(50)] = 948,
  [SMALL_STATE(51)] = 962,
  [SMALL_STATE(52)] = 970,
  [SMALL_STATE(53)] = 977,
  [SMALL_STATE(54)] = 990,
  [SMALL_STATE(55)] = 997,
  [SMALL_STATE(56)] = 1010,
  [SMALL_STATE(57)] = 1017,
  [SMALL_STATE(58)] = 1024,
  [SMALL_STATE(59)] = 1034,
  [SMALL_STATE(60)] = 1044,
  [SMALL_STATE(61)] = 1054,
  [SMALL_STATE(62)] = 1059,
  [SMALL_STATE(63)] = 1066,
  [SMALL_STATE(64)] = 1073,
  [SMALL_STATE(65)] = 1078,
  [SMALL_STATE(66)] = 1085,
  [SMALL_STATE(67)] = 1092,
  [SMALL_STATE(68)] = 1097,
  [SMALL_STATE(69)] = 1102,
  [SMALL_STATE(70)] = 1106,
  [SMALL_STATE(71)] = 1110,
  [SMALL_STATE(72)] = 1114,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 9),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 1, 0, 2),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mods, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mods_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mods_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mods_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mods_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 1, 0, 12),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 1, 0, 5),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 2, 0, 12),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 1, 0, 13),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 2, 0, 5),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defaults, 2, 0, 13),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 1, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 1, 0, 3),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 2, 0, 7),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 3, 0, 10),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_target_repeat1, 2, 0, 19),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_target_repeat1, 2, 0, 19), SHIFT_REPEAT(62),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rpe, 2, 0, 14),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weight, 2, 0, 15),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 2, 0, 4),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_percent, 2, 0, 16),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_target_repeat1, 2, 0, 17),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 4, 0, 20),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 3, 0, 18),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rest, 2, 0, 15),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 2, 0, 6),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__weight_first, 2, 0, 15),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__legacy_weight, 3, 0, 22),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__percent_first, 2, 0, 16),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rpe, 3, 0, 23),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__mod, 1, 0, 5),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weight, 3, 0, 24),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_percent, 3, 0, 25),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__percent_first, 3, 0, 25),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 3, 0, 8),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rest_first, 2, 0, 15),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 4, 0, 8),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__weight_first, 3, 0, 24),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 2, 0, 2),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 4, 0, 9),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 4, 0, 21),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 3, 0, 11),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 5, 0, 26),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 6, 0, 27),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [217] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_workline(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "workline",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 4,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
